POST https://localhost:7035/api/filme/cadastrar
Content-Type: application/json

{ 
  "filmeID": ,
  "nome": " Vorazes",
  "classif_ind": 0,
  "ano_lanc": 2023,
  "alugado": false,
  "genero": {
    "generoID": 1,
    "generoNome": ""
  },
  "generoID": 0

}
### listar todos os Usuarios
GET https://localhost:7035/api/filme/listar

### lista de filmes alugados
GET https://localhost:7035/api/filme/listarAlugados

### lista de filmes disponiveis
GET https://localhost:7035/api/filme/listardisponiveis